import { LicenseCategory, LicensePolicy, PolicyAction, ApprovedPackagesRegistry } from "./types";

/**
 * Known license mappings for common packages, keyed by ecosystem then lowercase package name.
 * Since this extension runs in the browser (no external API calls), this static registry
 * provides license resolution for popular packages.
 *
 * NuGet section is the most comprehensive since the company primarily uses C#/.NET.
 */
export const KNOWN_LICENSES: Record<string, Record<string, string>> = {
  nuget: {
    // Serialization & JSON
    "newtonsoft.json": "MIT",
    "system.text.json": "MIT",
    "messagePack": "MIT",
    "protobuf-net": "Apache-2.0",
    "yamldotnet": "MIT",

    // Logging
    "serilog": "Apache-2.0",
    "serilog.sinks.console": "Apache-2.0",
    "serilog.sinks.file": "Apache-2.0",
    "serilog.sinks.seq": "Apache-2.0",
    "serilog.aspnetcore": "Apache-2.0",
    "serilog.extensions.logging": "Apache-2.0",
    "serilog.settings.configuration": "Apache-2.0",
    "serilog.enrichers.environment": "Apache-2.0",
    "serilog.enrichers.thread": "Apache-2.0",
    "nlog": "BSD-3-Clause",
    "log4net": "Apache-2.0",
    "microsoft.extensions.logging": "MIT",
    "microsoft.extensions.logging.abstractions": "MIT",
    "microsoft.extensions.logging.console": "MIT",

    // Microsoft .NET / ASP.NET Core
    "microsoft.aspnetcore.mvc": "MIT",
    "microsoft.aspnetcore.app": "MIT",
    "microsoft.aspnetcore.authentication.jwtbearer": "MIT",
    "microsoft.aspnetcore.identity": "MIT",
    "microsoft.aspnetcore.authorization": "MIT",
    "microsoft.extensions.dependencyinjection": "MIT",
    "microsoft.extensions.dependencyinjection.abstractions": "MIT",
    "microsoft.extensions.configuration": "MIT",
    "microsoft.extensions.configuration.json": "MIT",
    "microsoft.extensions.configuration.environmentvariables": "MIT",
    "microsoft.extensions.configuration.abstractions": "MIT",
    "microsoft.extensions.configuration.binder": "MIT",
    "microsoft.extensions.options": "MIT",
    "microsoft.extensions.options.configurationextensions": "MIT",
    "microsoft.extensions.hosting": "MIT",
    "microsoft.extensions.hosting.abstractions": "MIT",
    "microsoft.extensions.http": "MIT",
    "microsoft.extensions.http.polly": "MIT",
    "microsoft.extensions.caching.memory": "MIT",
    "microsoft.extensions.caching.stackexchangeredis": "MIT",
    "microsoft.extensions.caching.abstractions": "MIT",
    "microsoft.extensions.fileproviders.physical": "MIT",
    "microsoft.extensions.primitives": "MIT",
    "microsoft.net.http.headers": "MIT",
    "microsoft.identitymodel.tokens": "MIT",
    "microsoft.identitymodel.jsonwebtokens": "MIT",
    "system.identitymodel.tokens.jwt": "MIT",

    // Entity Framework & Data Access
    "microsoft.entityframeworkcore": "MIT",
    "microsoft.entityframeworkcore.sqlserver": "MIT",
    "microsoft.entityframeworkcore.design": "MIT",
    "microsoft.entityframeworkcore.tools": "MIT",
    "microsoft.entityframeworkcore.relational": "MIT",
    "microsoft.entityframeworkcore.inmemory": "MIT",
    "microsoft.entityframeworkcore.sqlite": "MIT",
    "microsoft.entityframeworkcore.proxies": "MIT",
    "npgsql.entityframeworkcore.postgresql": "PostgreSQL",
    "pomelo.entityframeworkcore.mysql": "MIT",
    "dapper": "Apache-2.0",
    "dapper.contrib": "Apache-2.0",
    "microsoft.data.sqlclient": "MIT",
    "system.data.sqlclient": "MIT",
    "npgsql": "PostgreSQL",
    "mysqlconnector": "MIT",
    "stackexchange.redis": "MIT",
    "mongodb.driver": "Apache-2.0",

    // Validation & Mapping
    "fluentvalidation": "Apache-2.0",
    "fluentvalidation.aspnetcore": "Apache-2.0",
    "fluentvalidation.dependencyinjectionextensions": "Apache-2.0",
    "automapper": "MIT",
    "automapper.extensions.microsoft.dependencyinjection": "MIT",
    "mapster": "MIT",

    // HTTP & API
    "polly": "BSD-3-Clause",
    "polly.extensions.http": "BSD-3-Clause",
    "microsoft.aspnet.webapi.client": "MIT",
    "refit": "MIT",
    "restsharp": "Apache-2.0",
    "flurl": "MIT",
    "flurl.http": "MIT",

    // Messaging & Events
    "mediatr": "Apache-2.0",
    "mediatr.extensions.microsoft.dependencyinjection": "Apache-2.0",
    "masstransit": "Apache-2.0",
    "masstransit.rabbitmq": "Apache-2.0",
    "masstransit.azure.servicebus.core": "Apache-2.0",
    "rabbitmq.client": "Apache-2.0",
    "azure.messaging.servicebus": "MIT",
    "azure.messaging.eventhubs": "MIT",
    "confluent.kafka": "Apache-2.0",

    // Azure SDK
    "azure.storage.blobs": "MIT",
    "azure.storage.queues": "MIT",
    "azure.storage.files.shares": "MIT",
    "azure.identity": "MIT",
    "azure.security.keyvault.secrets": "MIT",
    "azure.security.keyvault.keys": "MIT",
    "azure.security.keyvault.certificates": "MIT",
    "azure.core": "MIT",
    "azure.extensions.aspnetcore.configuration.secrets": "MIT",
    "microsoft.azure.cosmos": "MIT",
    "microsoft.azure.servicebus": "MIT",
    "microsoft.applicationinsights": "MIT",
    "microsoft.applicationinsights.aspnetcore": "MIT",

    // Testing
    "xunit": "Apache-2.0",
    "xunit.runner.visualstudio": "Apache-2.0",
    "xunit.assert": "Apache-2.0",
    "nunit": "MIT",
    "nunit3testadapter": "MIT",
    "mstest.testframework": "MIT",
    "mstest.testadapter": "MIT",
    "moq": "BSD-3-Clause",
    "nsubstitute": "BSD-3-Clause",
    "fakeiteasy": "MIT",
    "bogus": "MIT",
    "autofixture": "MIT",
    "fluentassertions": "Apache-2.0",
    "shouldly": "BSD-2-Clause",
    "coverlet.collector": "MIT",
    "microsoft.net.test.sdk": "MIT",
    "microsoft.aspnetcore.mvc.testing": "MIT",
    "testcontainers": "MIT",
    "wiremock.net": "Apache-2.0",

    // Dependency Injection
    "autofac": "MIT",
    "autofac.extensions.dependencyinjection": "MIT",
    "ninject": "Apache-2.0",
    "simpleinjector": "MIT",
    "lamar": "MIT",

    // Scheduling
    "hangfire": "LGPL-3.0-only",
    "hangfire.core": "LGPL-3.0-only",
    "hangfire.aspnetcore": "LGPL-3.0-only",
    "hangfire.sqlserver": "LGPL-3.0-only",
    "quartz": "Apache-2.0",

    // Swagger / OpenAPI
    "swashbuckle.aspnetcore": "MIT",
    "swashbuckle.aspnetcore.swagger": "MIT",
    "swashbuckle.aspnetcore.swaggergen": "MIT",
    "swashbuckle.aspnetcore.swaggerui": "MIT",
    "nswag.aspnetcore": "MIT",

    // Health Checks
    "aspnetcore.healthchecks.sqlserver": "Apache-2.0",
    "aspnetcore.healthchecks.redis": "Apache-2.0",
    "aspnetcore.healthchecks.rabbitmq": "Apache-2.0",
    "aspnetcore.healthchecks.ui": "Apache-2.0",
    "microsoft.extensions.diagnostics.healthchecks": "MIT",

    // Security & Auth
    "identityserver4": "Apache-2.0",
    "duende.identityserver": "RPL-1.5",
    "bcrypt.net-next": "MIT",
    "microsoft.aspnetcore.dataprotection": "MIT",

    // gRPC
    "grpc.aspnetcore": "Apache-2.0",
    "grpc.tools": "Apache-2.0",
    "grpc.net.client": "Apache-2.0",
    "google.protobuf": "BSD-3-Clause",

    // Other common packages
    "humanizer": "MIT",
    "humanizer.core": "MIT",
    "csvhelper": "Apache-2.0",
    "closedxml": "MIT",
    "epplus": "Polyform-Noncommercial-1.0.0",
    "npoi": "Apache-2.0",
    "imageSharp": "Apache-2.0",
    "sixlabors.imagesharp": "Apache-2.0",
    "markdig": "BSD-2-Clause",
    "mimekit": "MIT",
    "mailkit": "MIT",
    "sendgrid": "MIT",
    "twilio": "MIT",
    "braintree": "MIT",
    "stripe.net": "Apache-2.0",
    "benchmarkdotnet": "MIT",
    "castle.core": "Apache-2.0",
    "system.reactive": "MIT",
    "hashids.net": "MIT",
    "miniprofiler.aspnetcore.mvc": "MIT",
    "scrutor": "MIT",
    "guardian.net": "MIT",
  },
  npm: {
    react: "MIT",
    "react-dom": "MIT",
    "react-router": "MIT",
    "react-router-dom": "MIT",
    next: "MIT",
    vue: "MIT",
    angular: "MIT",
    svelte: "MIT",
    express: "MIT",
    fastify: "MIT",
    koa: "MIT",
    lodash: "MIT",
    underscore: "MIT",
    ramda: "MIT",
    axios: "MIT",
    "node-fetch": "MIT",
    typescript: "Apache-2.0",
    webpack: "MIT",
    vite: "MIT",
    esbuild: "MIT",
    rollup: "MIT",
    parcel: "MIT",
    babel: "MIT",
    eslint: "MIT",
    prettier: "MIT",
    jest: "MIT",
    mocha: "MIT",
    vitest: "MIT",
    cypress: "MIT",
    playwright: "Apache-2.0",
    moment: "MIT",
    "date-fns": "MIT",
    dayjs: "MIT",
    luxon: "MIT",
    d3: "ISC",
    "chart.js": "MIT",
    "three.js": "MIT",
    tailwindcss: "MIT",
    "styled-components": "MIT",
    emotion: "MIT",
    "material-ui": "MIT",
    "@mui/material": "MIT",
    "ant-design": "MIT",
    antd: "MIT",
    zod: "MIT",
    yup: "MIT",
    joi: "BSD-3-Clause",
    ajv: "MIT",
    commander: "MIT",
    chalk: "MIT",
    inquirer: "MIT",
    dotenv: "BSD-2-Clause",
    cors: "MIT",
    helmet: "MIT",
    "body-parser": "MIT",
    "cookie-parser": "MIT",
    jsonwebtoken: "MIT",
    bcrypt: "MIT",
    passport: "MIT",
    mongoose: "MIT",
    sequelize: "MIT",
    typeorm: "MIT",
    prisma: "Apache-2.0",
    "@prisma/client": "Apache-2.0",
    knex: "MIT",
    pg: "MIT",
    mysql2: "MIT",
    redis: "MIT",
    ioredis: "MIT",
    "socket.io": "MIT",
    ws: "MIT",
    uuid: "MIT",
    nanoid: "MIT",
    rxjs: "Apache-2.0",
    immer: "MIT",
    zustand: "MIT",
    redux: "MIT",
    "@reduxjs/toolkit": "MIT",
    mobx: "MIT",
    "react-query": "MIT",
    "@tanstack/react-query": "MIT",
    swr: "MIT",
    sharp: "Apache-2.0",
    "azure-devops-extension-api": "MIT",
    "azure-devops-extension-sdk": "MIT",
    "azure-devops-ui": "MIT",
  },
  go: {
    "github.com/gin-gonic/gin": "MIT",
    "github.com/gorilla/mux": "BSD-3-Clause",
    "github.com/gorilla/websocket": "BSD-2-Clause",
    "github.com/labstack/echo": "MIT",
    "github.com/go-chi/chi": "MIT",
    "github.com/stretchr/testify": "MIT",
    "github.com/sirupsen/logrus": "MIT",
    "go.uber.org/zap": "MIT",
    "github.com/spf13/cobra": "Apache-2.0",
    "github.com/spf13/viper": "MIT",
    "google.golang.org/grpc": "Apache-2.0",
    "google.golang.org/protobuf": "BSD-3-Clause",
    "github.com/go-sql-driver/mysql": "MPL-2.0",
    "github.com/lib/pq": "MIT",
    "github.com/jackc/pgx": "MIT",
    "github.com/go-redis/redis": "BSD-2-Clause",
    "gorm.io/gorm": "MIT",
    "github.com/dgrijalva/jwt-go": "MIT",
    "github.com/golang-jwt/jwt": "MIT",
    "github.com/google/uuid": "BSD-3-Clause",
    "github.com/prometheus/client_golang": "Apache-2.0",
    "github.com/hashicorp/consul": "MPL-2.0",
    "github.com/hashicorp/vault": "MPL-2.0",
    "github.com/aws/aws-sdk-go": "Apache-2.0",
    "github.com/Azure/azure-sdk-for-go": "MIT",
  },
  python: {
    requests: "Apache-2.0",
    flask: "BSD-3-Clause",
    django: "BSD-3-Clause",
    fastapi: "MIT",
    uvicorn: "BSD-3-Clause",
    starlette: "BSD-3-Clause",
    numpy: "BSD-3-Clause",
    pandas: "BSD-3-Clause",
    scipy: "BSD-3-Clause",
    matplotlib: "PSF-2.0",
    scikit_learn: "BSD-3-Clause",
    "scikit-learn": "BSD-3-Clause",
    tensorflow: "Apache-2.0",
    pytorch: "BSD-3-Clause",
    torch: "BSD-3-Clause",
    pytest: "MIT",
    pytest_cov: "MIT",
    "pytest-cov": "MIT",
    sqlalchemy: "MIT",
    alembic: "MIT",
    celery: "BSD-3-Clause",
    redis: "MIT",
    boto3: "Apache-2.0",
    botocore: "Apache-2.0",
    pydantic: "MIT",
    httpx: "BSD-3-Clause",
    aiohttp: "Apache-2.0",
    pillow: "MIT-CMU",
    cryptography: "Apache-2.0",
    bcrypt: "Apache-2.0",
    pyjwt: "MIT",
    click: "BSD-3-Clause",
    typer: "MIT",
    gunicorn: "MIT",
    psycopg2: "LGPL-3.0-only",
    "psycopg2-binary": "LGPL-3.0-only",
    black: "MIT",
    flake8: "MIT",
    mypy: "MIT",
    ruff: "MIT",
    setuptools: "MIT",
    wheel: "MIT",
    pip: "MIT",
  },
  maven: {
    "com.google.guava:guava": "Apache-2.0",
    "org.slf4j:slf4j-api": "MIT",
    "org.apache.commons:commons-lang3": "Apache-2.0",
    "org.apache.commons:commons-collections4": "Apache-2.0",
    "org.apache.commons:commons-io": "Apache-2.0",
    "junit:junit": "EPL-1.0",
    "org.junit.jupiter:junit-jupiter": "EPL-2.0",
    "org.mockito:mockito-core": "MIT",
    "org.assertj:assertj-core": "Apache-2.0",
    "org.springframework:spring-core": "Apache-2.0",
    "org.springframework:spring-context": "Apache-2.0",
    "org.springframework:spring-web": "Apache-2.0",
    "org.springframework.boot:spring-boot": "Apache-2.0",
    "org.springframework.boot:spring-boot-starter-web": "Apache-2.0",
    "com.fasterxml.jackson.core:jackson-core": "Apache-2.0",
    "com.fasterxml.jackson.core:jackson-databind": "Apache-2.0",
    "com.fasterxml.jackson.core:jackson-annotations": "Apache-2.0",
    "org.projectlombok:lombok": "MIT",
    "ch.qos.logback:logback-classic": "EPL-1.0",
    "org.apache.logging.log4j:log4j-core": "Apache-2.0",
    "org.apache.httpcomponents:httpclient": "Apache-2.0",
    "com.squareup.okhttp3:okhttp": "Apache-2.0",
    "io.netty:netty-all": "Apache-2.0",
    "org.apache.kafka:kafka-clients": "Apache-2.0",
    "com.google.code.gson:gson": "Apache-2.0",
    "org.hibernate:hibernate-core": "LGPL-2.1-only",
    "mysql:mysql-connector-java": "GPL-2.0-only",
    "org.postgresql:postgresql": "BSD-2-Clause",
    "redis.clients:jedis": "MIT",
    "io.jsonwebtoken:jjwt": "Apache-2.0",
  },
};

/**
 * Maps SPDX license identifiers to license categories.
 */
export const LICENSE_CATEGORIES: Record<string, LicenseCategory> = {
  // Permissive
  MIT: LicenseCategory.Permissive,
  "MIT-CMU": LicenseCategory.Permissive,
  "Apache-2.0": LicenseCategory.Permissive,
  "BSD-2-Clause": LicenseCategory.Permissive,
  "BSD-3-Clause": LicenseCategory.Permissive,
  ISC: LicenseCategory.Permissive,
  Unlicense: LicenseCategory.Permissive,
  "CC0-1.0": LicenseCategory.Permissive,
  "0BSD": LicenseCategory.Permissive,
  Zlib: LicenseCategory.Permissive,
  "BSL-1.0": LicenseCategory.Permissive,
  PostgreSQL: LicenseCategory.Permissive,
  "PSF-2.0": LicenseCategory.Permissive,
  "Artistic-2.0": LicenseCategory.Permissive,
  "MS-PL": LicenseCategory.Permissive,
  WTFPL: LicenseCategory.Permissive,
  "BlueOak-1.0.0": LicenseCategory.Permissive,

  // Weak Copyleft
  "LGPL-2.1-only": LicenseCategory.WeakCopyleft,
  "LGPL-2.1-or-later": LicenseCategory.WeakCopyleft,
  "LGPL-3.0-only": LicenseCategory.WeakCopyleft,
  "LGPL-3.0-or-later": LicenseCategory.WeakCopyleft,
  "MPL-2.0": LicenseCategory.WeakCopyleft,
  "EPL-1.0": LicenseCategory.WeakCopyleft,
  "EPL-2.0": LicenseCategory.WeakCopyleft,
  "CDDL-1.0": LicenseCategory.WeakCopyleft,
  "CDDL-1.1": LicenseCategory.WeakCopyleft,
  "CPL-1.0": LicenseCategory.WeakCopyleft,
  "MS-RL": LicenseCategory.WeakCopyleft,

  // Strong Copyleft
  "GPL-2.0-only": LicenseCategory.StrongCopyleft,
  "GPL-2.0-or-later": LicenseCategory.StrongCopyleft,
  "GPL-3.0-only": LicenseCategory.StrongCopyleft,
  "GPL-3.0-or-later": LicenseCategory.StrongCopyleft,
  "AGPL-3.0-only": LicenseCategory.StrongCopyleft,
  "AGPL-3.0-or-later": LicenseCategory.StrongCopyleft,
  "SSPL-1.0": LicenseCategory.StrongCopyleft,
  "OSL-3.0": LicenseCategory.StrongCopyleft,
  "EUPL-1.2": LicenseCategory.StrongCopyleft,

  // Proprietary / Restrictive
  "RPL-1.5": LicenseCategory.Proprietary,
  "Polyform-Noncommercial-1.0.0": LicenseCategory.Proprietary,
  "BUSL-1.1": LicenseCategory.Proprietary,
};

/**
 * Default license policy for the organization.
 * Permissive: allowed. Weak copyleft: warn. Strong copyleft: blocked. Unknown: warn.
 */
export const DEFAULT_POLICY: LicensePolicy = {
  categoryDefaults: {
    [LicenseCategory.Permissive]: PolicyAction.Allow,
    [LicenseCategory.WeakCopyleft]: PolicyAction.Warn,
    [LicenseCategory.StrongCopyleft]: PolicyAction.Block,
    [LicenseCategory.Proprietary]: PolicyAction.Warn,
    [LicenseCategory.Unknown]: PolicyAction.Warn,
  },
  specificOverrides: [],
  excludedPackages: [],
};

export const DEFAULT_APPROVED_PACKAGES_REGISTRY: ApprovedPackagesRegistry = {
  packages: [],
  autoApprovalRules: [],
};
